SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS: int = 20
ASTEROID_KINDS: int = 3
ASTEROID_SPAWN_RATE: float = 0.8
ASTEROID_MAX_RADIUS: int = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS: int = 20
PLAYER_ROTATION_SPEED: float = 300.0  # degrees per second
PLAYER_THRUST: float = 200.0  # pixels per second squared
